export const READ_LIBRARY_FILE = 'readLibraryFile'
export const READ_SETTINGS_FILE = 'readSettingsFile'
export const WRITE_SETTINGS_FILE = 'writeSettingsFile'
export const ADD_BOOK_DIRECTORY = 'addBookDirectory'
export const SAVE_BOOK_PROGRESS = 'saveBookProgress'
