import { app, BrowserWindow, ipcMain, dialog, protocol, net } from 'electron';
import { startScan, cancelScan, loadLibrary, saveLibrary, removeBooksByDirectory, loadDirectories, saveDirectories } from './scanner/manager';
import * as fs from 'fs';
import * as path from 'path';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

// Register custom protocol for serving cover images from the filesystem
protocol.registerSchemesAsPrivileged([
  { scheme: 'audiobook-cover', privileges: { bypassCSP: true, supportFetchAPI: true } },
  { scheme: 'audiobook-file', privileges: { bypassCSP: true, supportFetchAPI: true, stream: true } },
]);

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 800,
    width: 1200,
    minWidth: 900,
    minHeight: 600,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  mainWindow.webContents.openDevTools();
};

// IPC Handlers
ipcMain.handle('dialog:openDirectory', async () => {
  const result = await dialog.showOpenDialog({
    properties: ['openDirectory'],
  });
  if (result.canceled || result.filePaths.length === 0) return null;
  return result.filePaths[0];
});

ipcMain.handle('scanner:start', async (event, directories: string[]) => {
  const win = BrowserWindow.fromWebContents(event.sender);
  if (win) startScan(directories, win);
});

ipcMain.handle('scanner:cancel', async () => {
  cancelScan();
});

ipcMain.handle('library:load', async () => {
  return loadLibrary();
});

ipcMain.handle('library:removeByDirectory', async (_event, directory: string) => {
  return removeBooksByDirectory(directory);
});

ipcMain.handle('library:save', async (_event, books) => {
  saveLibrary(books);
});

ipcMain.handle('directories:load', async () => {
  return loadDirectories();
});

ipcMain.handle('directories:save', async (_event, dirs: string[]) => {
  saveDirectories(dirs);
});

app.on('ready', () => {
  // Register the audiobook-cover protocol handler
  protocol.handle('audiobook-cover', (request) => {
    const filePath = decodeURIComponent(request.url.replace('audiobook-cover://', ''));
    return net.fetch(`file://${filePath}`);
  });

  protocol.handle('audiobook-file', async (request) => {
    const filePath = decodeURIComponent(request.url.replace('audiobook-file://', ''));

    try {
      const stat = fs.statSync(filePath);
      const fileSize = stat.size;
      const ext = path.extname(filePath).toLowerCase();
      const mimeTypes: Record<string, string> = {
        '.mp3': 'audio/mpeg', '.m4a': 'audio/mp4', '.m4b': 'audio/mp4',
        '.flac': 'audio/flac', '.ogg': 'audio/ogg', '.opus': 'audio/opus',
        '.wav': 'audio/wav', '.aac': 'audio/aac', '.wma': 'audio/x-ms-wma',
      };
      const contentType = mimeTypes[ext] || 'application/octet-stream';
      const rangeHeader = request.headers.get('Range');

      if (rangeHeader) {
        const match = rangeHeader.match(/bytes=(\d+)-(\d*)/);
        if (match) {
          const start = parseInt(match[1], 10);
          const end = match[2] ? parseInt(match[2], 10) : fileSize - 1;
          const chunkSize = end - start + 1;
          const stream = fs.createReadStream(filePath, { start, end });
          const chunks: Buffer[] = [];
          for await (const chunk of stream) {
            chunks.push(chunk as Buffer);
          }
          const body = Buffer.concat(chunks);

          return new Response(body, {
            status: 206,
            headers: {
              'Content-Range': `bytes ${start}-${end}/${fileSize}`,
              'Accept-Ranges': 'bytes',
              'Content-Length': String(chunkSize),
              'Content-Type': contentType,
            },
          });
        }
      }

      // No Range header — serve full file
      const body = fs.readFileSync(filePath);
      return new Response(body, {
        status: 200,
        headers: {
          'Accept-Ranges': 'bytes',
          'Content-Length': String(fileSize),
          'Content-Type': contentType,
        },
      });
    } catch (err) {
      console.error('[audiobook-file] Error serving:', filePath, err);
      return new Response('File not found', { status: 404 });
    }
  });

  createWindow();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});
