import { app, BrowserWindow, ipcMain, dialog, protocol, net } from 'electron';
import { startScan, cancelScan, loadLibrary, removeBooksByDirectory, loadDirectories, saveDirectories } from './scanner/manager';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

// Register custom protocol for serving cover images from the filesystem
protocol.registerSchemesAsPrivileged([
  { scheme: 'audiobook-cover', privileges: { bypassCSP: true, supportFetchAPI: true } },
]);

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 800,
    width: 1200,
    minWidth: 900,
    minHeight: 600,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  mainWindow.webContents.openDevTools();
};

// IPC Handlers
ipcMain.handle('dialog:openDirectory', async () => {
  const result = await dialog.showOpenDialog({
    properties: ['openDirectory'],
  });
  if (result.canceled || result.filePaths.length === 0) return null;
  return result.filePaths[0];
});

ipcMain.handle('scanner:start', async (event, directories: string[]) => {
  const win = BrowserWindow.fromWebContents(event.sender);
  if (win) startScan(directories, win);
});

ipcMain.handle('scanner:cancel', async () => {
  cancelScan();
});

ipcMain.handle('library:load', async () => {
  return loadLibrary();
});

ipcMain.handle('library:removeByDirectory', async (_event, directory: string) => {
  return removeBooksByDirectory(directory);
});

ipcMain.handle('directories:load', async () => {
  return loadDirectories();
});

ipcMain.handle('directories:save', async (_event, dirs: string[]) => {
  saveDirectories(dirs);
});

app.on('ready', () => {
  // Register the audiobook-cover protocol handler
  protocol.handle('audiobook-cover', (request) => {
    const filePath = decodeURIComponent(request.url.replace('audiobook-cover://', ''));
    return net.fetch(`file://${filePath}`);
  });

  createWindow();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});
